### ISSUE TITLE
Reproduction number R0 depends on language?!

### ISSUE THREAD

**Issue by tomdierkes** [MTGermany/CoronaSim#2]
Hi, playing around with your really nice simulation tool, I have encountered that the reproduction number R0 apparently depends on the actual language of the simulation page. Any clues for this unexpected behaviour? Well, R0 is an estimated value, that's fine (and well understood!), however, at the same time, somehow a quite central (and sensitive) value as well... just too important to not  be consistent, I would presume. That apart, you did a tremendous job!

**Comment by MTGermany** [comment]
Hello Tom, thanks for giving feedback. Language-dependent R values clearly should not happen! However, I could not reproduce this behavior. It is also not expected because I only work on one simulator version and produce the English version just by a script replacing strings in the html and js files (it is in the repo, ger2eng.sh). Moreover, the data used by the simulator are exactly the same for both languages. 
Possibly you have a cache of the  simulation code for one language but not for the other?  Please check if this behavior persists after you have emptied your cache. If so, please give information when and where this happens (simulated country, displayed window, any prior actions taken after loading the simulation such as changing the sliders or re-calibrating), ideally visualized by two screenshots. 
Best,
Martin

**Comment by tomdierkes** [comment]
Hi Martin, good news: I cannot reproduce the effect either! Too bad that I was too lazy to provide any screenshots on Dec 22. My fault! So now you simply have to trust me that there _was_ the effect to be observed. The procedure to repeat was easy enough: Calling your starting web page of the simulator, let it run and then switch over to (american?) English. After repeating this several times my explanation for the odd outcome went also into the direction of some (hidden?) side effects, e.g. different loop counting or similar, but as I am absolutely not experienced in JS, this issue was born. In the mean time I have noticed you have worked a bit on the code (for example, the "lockdown" slider disappeared in the measures view), and all numbers are now consistent! As far as I can see.... 

Well, as the issue seems to be settled by now, please apologise for all the fuzz.
Pretty good work anyway!!

Cheers,
.tom

**Comment by MTGermany** [comment]
Yes, I have removed the "lockdown slider for two reasons: 1. The degree of lockdown cannot be consistently obtained from the data, 2. The factor on the R0 value for the different measures cannot be estimated in a sound way (partly because of the  lack of automatic data). 
  
  
   
    Thomas Dierkes <notifications@github.com> hat am 19.01.2021 14:16 geschrieben:
   
   
    
   
   
    
   
   
   Hi Martin, good news: I cannot reproduce the effect either! Too bad that I was too lazy to provide any screenshots on Dec 22. My fault! So now you simply have to trust me that there was the effect to be observed. The procedure to repeat was easy enough: Calling your starting web page of the simulator, let it run and then switch over to (american?) English. After repeating this several times my explanation for the odd outcome went also into the direction of some (hidden?) side effects, e.g. different loop counting or similar, but as I am absolutely not experienced in JS, this issue was born. In the mean time I have noticed you have worked a bit on the code (for example, the "lockdown" slider disappeared in the measures view), and all numbers are now consistent! As far as I can see....
   Well, as the issue seems to be settled by now, please apologise for all the fuzz.Pretty good work anyway!!
   Cheers,.tom
